services:
  rustexample:
    image: rust:latest
    volumes:
      - type: bind
        source: /home/drone/git/morning_alarm/
        target: /home/drone/git/morning_alarm/ 
    build:
      context: ./src/
    develop:
      watch:
        - action: rebuild
          path: ./src/
          ignore:
            - ./target/

